default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff
        require_serial: true
        language: system
        types: [python]
      - id: ruff-nb
        name: ruff-nb
        entry: uv run nbqa ruff .
        require_serial: true
        language: system
        pass_filenames: false
        types: [python]
      - id: black
        name: black
        entry: uv run black
        require_serial: true
        language: system
        types: [python]
      - id: uv-lock-check
        name: uv lock check
        entry: uv lock --check
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy tianshou examples test
        # filenames should not be passed as they would collide with the config in pyproject.toml
        pass_filenames: false
        files: '^tianshou(/[^/]*)*/[^/]*\.py$'
        language: system
      - id: mypy-nb
        name: mypy-nb
        entry: uv run nbqa mypy
        language: system
