# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - python -m pip install uv
    - uv sync --extra eval --dev
    - uv run python docs/autogen_rst.py
    - uv run which jupyter-book
    - uv run python docs/create_toc.py
    - uv run jupyter-book config sphinx docs/
    - uv run sphinx-build -W -b html docs $READTHEDOCS_OUTPUT/html
