name: Check Formatting/Typing and Build Docs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
        - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true
      - name: Install the project dependencies
        run: |
          uv sync --locked --extra eval --dev
      - name: Check formatting
        run: uv run poe lint
      - name: Check typing
        run: uv run poe type-check
      - name: Build docs
        run: MYSTNB_DEBUG=1 uv run poe doc-build
      - name: Show errors (if any)
        if: failure()
        run: find docs/_build/reports -name "*.err.log" -exec echo "--- {} ---" \; -exec cat {} \;
